pipeline:
    reader:
        - reader.EDRReader
        - file_path: "test_data/15.1-EX_XML_EDR_UO.xml"
    preprocessor:
        - preprocessor.PreProcessor
        - tokenizer: "!tokenize_uk.tokenize_words"

    beneficiary_categorizer:
        - categorizer.HasBeneficiaryOwnershipRecord

    parser:
        - record_parser.HeuristicBasedParser
        # - record_parser.EnsembleBasedParser
        # - voters:
        #     - "!record_parser.HeuristicBasedParser"
        #     - "!record_parser.MITIEBasedParser"
        # - cutoff: 0

output_csv: test_data/output.csv
limit: 10000
export_only_beneficial_owners: True